title: rock-band-scratch2
hero_image: images/banner.png
description: rock-band-scratch2 description
version: 4
listed: false
copyedit: false
last_tested: "2018-11-26"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
