hero_image: images/hero-rock-band-large.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Rock bend
description: U ovom projektu naučit ćeš kako programirati vlastite glazbene instrumente!
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
interests: ''
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-10-01
steps: 
- title: Rock bend