---
hero_image: images/hero-rock-band-large.png
theme: red
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Banda de Rock
description: Aprenda a programar os seus próprios instrumentos musicais
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
interests: ''
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-10-01
steps:
  - title: Introdução
  - title: O que você vai precisar
  - title: Atores
  - title: O palco
  - title: Fazendo um tambor
  - title: "Desafio: Melhore o seu tambor"
  - title: Fazendo um cantor(a)
  - title: Fantasias
  - title: "Desafio: Mude a fantasia do seu tambor"
  - title: "Desafio: Faça a sua própria banda"
